//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CryptoWebscraperMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CryptoCurrency
    {
        public int Code { get; set; }
        public int Item { get; set; }
        public string Name { get; set; }
        public string MarketCap { get; set; }
        public string Price { get; set; }
        public string Volume { get; set; }
        public string Supply { get; set; }
        public string Change { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public string DateTimeStr
        {
            get
            {
                return TimeStamp.ToString("MM/dd/yyyy HH:mm:ss.fff");
            }
        }
    }
}
